//! String ordering that matches what the TypeScript implementation produced.
//!
//! The old code sorted with `String.prototype.localeCompare`, in two flavours:
//! plain (manga names, chapter names, page filenames in a directory) and
//! `{ numeric: true }` (page filenames inside a zip chapter, so `page2` sorts
//! before `page10`). A byte-wise `str::cmp` is not a drop-in replacement — it
//! puts every uppercase letter ahead of every lowercase one, sorts `Émile`
//! after `zzz`, and orders punctuation by codepoint — so switching to it would
//! visibly reshuffle existing libraries.
//!
//! This is an approximation of ICU root collation covering what actually turns
//! up in filenames, verified against `Intl`'s real output (see the corpus test
//! at the bottom, whose expected orders were generated by the JS engine):
//!
//! - **primary**: punctuation < digits < letters, accents and case ignored,
//!   with punctuation in ICU's order rather than ASCII's (`_` sorts before `-`);
//! - **secondary**: unaccented before accented (`emile` < `Émile`);
//! - **tertiary**: lowercase before uppercase (`a` < `A`);
//! - **quaternary**: under numeric collation, equal-valued digit runs order by
//!   how many leading zeros they carry (`1` < `01` < `001`).
//!
//! What it does not reproduce is locale-specific tailoring (Swedish `å`,
//! Turkish dotless `ı`, and so on). `localeCompare` with no locale argument
//! uses the runtime's default locale, so the old code was already
//! machine-dependent there; root-collation behaviour is the stable choice.

use std::cmp::Ordering;

/// Equivalent of `a.localeCompare(b)`.
pub fn locale_cmp(a: &str, b: &str) -> Ordering {
  cmp_impl(a, b, false)
}

/// Equivalent of `a.localeCompare(b, undefined, { numeric: true })`.
pub fn natural_cmp(a: &str, b: &str) -> Ordering {
  cmp_impl(a, b, true)
}

/// ASCII punctuation and symbols in ICU root order, which is not codepoint
/// order: space sorts first, then `_` before `-`, and `$` sorts after `~`.
const PUNCT_ORDER: [char; 33] = [
  ' ', '_', '-', ',', ';', ':', '!', '?', '.', '\'', '"', '(', ')', '[', ']', '{', '}', '@', '*',
  '/', '\\', '&', '#', '%', '`', '^', '+', '<', '=', '>', '|', '~', '$',
];

/// Primary classes, ordered: punctuation and symbols, then digits, then letters.
const CLASS_PUNCT: u8 = 0;
const CLASS_DIGIT: u8 = 1;
const CLASS_LETTER: u8 = 2;

fn punct_rank(ch: char) -> Option<u32> {
  PUNCT_ORDER.iter().position(|c| *c == ch).map(|i| i as u32)
}

/// Base letter for every accented Latin character in `U+00C0..=U+024F`, or `0`
/// where there is no plain ASCII base (`Æ`, `ß`, `ø`, and the symbols).
///
/// Generated from Unicode NFD data. It exists instead of a general
/// normalisation dependency because that pulled 112KB of decomposition tables
/// into the wasm bundle to serve a range this table covers in 400 bytes.
/// Characters outside this range — CJK above all — carry no combining marks to
/// strip, so they pass through unchanged.
const DEACCENT_START: u32 = 0x00c0;
const DEACCENT: [u8; 400] = [
  b'A', b'A', b'A', b'A', b'A', b'A', 0, b'C', b'E', b'E', b'E', b'E', b'I', b'I', b'I', b'I', 0,
  b'N', b'O', b'O', b'O', b'O', b'O', 0, 0, b'U', b'U', b'U', b'U', b'Y', 0, 0, b'a', b'a', b'a',
  b'a', b'a', b'a', 0, b'c', b'e', b'e', b'e', b'e', b'i', b'i', b'i', b'i', 0, b'n', b'o', b'o',
  b'o', b'o', b'o', 0, 0, b'u', b'u', b'u', b'u', b'y', 0, b'y', b'A', b'a', b'A', b'a', b'A',
  b'a', b'C', b'c', b'C', b'c', b'C', b'c', b'C', b'c', b'D', b'd', 0, 0, b'E', b'e', b'E', b'e',
  b'E', b'e', b'E', b'e', b'E', b'e', b'G', b'g', b'G', b'g', b'G', b'g', b'G', b'g', b'H', b'h',
  0, 0, b'I', b'i', b'I', b'i', b'I', b'i', b'I', b'i', b'I', 0, 0, 0, b'J', b'j', b'K', b'k', 0,
  b'L', b'l', b'L', b'l', b'L', b'l', 0, 0, 0, 0, b'N', b'n', b'N', b'n', b'N', b'n', 0, 0, 0,
  b'O', b'o', b'O', b'o', b'O', b'o', 0, 0, b'R', b'r', b'R', b'r', b'R', b'r', b'S', b's', b'S',
  b's', b'S', b's', b'S', b's', b'T', b't', b'T', b't', 0, 0, b'U', b'u', b'U', b'u', b'U', b'u',
  b'U', b'u', b'U', b'u', b'U', b'u', b'W', b'w', b'Y', b'y', b'Y', b'Z', b'z', b'Z', b'z', b'Z',
  b'z', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, b'O', b'o', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, b'U', b'u', 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, b'A', b'a', b'I', b'i', b'O', b'o',
  b'U', b'u', b'U', b'u', b'U', b'u', b'U', b'u', b'U', b'u', 0, b'A', b'a', b'A', b'a', 0, 0, 0,
  0, b'G', b'g', b'K', b'k', b'O', b'o', b'O', b'o', 0, 0, b'j', 0, 0, 0, b'G', b'g', 0, 0, b'N',
  b'n', b'A', b'a', 0, 0, 0, 0, b'A', b'a', b'A', b'a', b'E', b'e', b'E', b'e', b'I', b'i', b'I',
  b'i', b'O', b'o', b'O', b'o', b'R', b'r', b'R', b'r', b'U', b'u', b'U', b'u', b'S', b's', b'T',
  b't', 0, 0, b'H', b'h', 0, 0, 0, 0, 0, 0, b'A', b'a', b'E', b'e', b'O', b'o', b'O', b'o', b'O',
  b'o', b'O', b'o', b'Y', b'y', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
];

/// Splits a character into its unaccented, lowercased base and an accent key,
/// so the primary pass can ignore accents and the secondary pass can order
/// them.
fn base_and_accent(ch: char) -> (char, u32) {
  let cp = ch as u32;
  let base = match cp
    .checked_sub(DEACCENT_START)
    .and_then(|i| DEACCENT.get(i as usize))
  {
    Some(&b) if b != 0 => b as char,
    _ => ch,
  };
  // Unaccented characters sort ahead of accented ones with the same base; two
  // different accents on one base fall back to codepoint order.
  let accent = if base == ch { 0 } else { cp };
  (base.to_lowercase().next().unwrap_or(base), accent)
}

fn primary_key(base: char) -> (u8, u32) {
  if let Some(rank) = punct_rank(base) {
    return (CLASS_PUNCT, rank);
  }
  if base.is_whitespace() {
    // Other whitespace groups with space, ahead of the punctuation table.
    return (CLASS_PUNCT, 0);
  }
  if base.is_numeric() {
    return (CLASS_DIGIT, base as u32);
  }
  if base.is_alphabetic() {
    return (CLASS_LETTER, base as u32);
  }
  // Unlisted symbols keep the punctuation class but sort after the known ones.
  (CLASS_PUNCT, PUNCT_ORDER.len() as u32 + base as u32)
}

#[derive(Debug)]
enum Token<'a> {
  /// A run of ASCII digits, compared by numeric value. Only produced under
  /// numeric collation.
  Digits(&'a str),
  Char {
    base: char,
    accent: u32,
    raw: char,
  },
}

fn tokenize(s: &str, numeric: bool) -> Vec<Token<'_>> {
  let mut out = Vec::new();
  let bytes = s.as_bytes();
  let mut i = 0;
  while i < s.len() {
    if numeric && bytes[i].is_ascii_digit() {
      let start = i;
      while i < s.len() && bytes[i].is_ascii_digit() {
        i += 1;
      }
      out.push(Token::Digits(&s[start..i]));
      continue;
    }
    let ch = s[i..].chars().next().expect("index is on a char boundary");
    let (base, accent) = base_and_accent(ch);
    out.push(Token::Char {
      base,
      accent,
      raw: ch,
    });
    i += ch.len_utf8();
  }
  out
}

/// Compares two digit runs by value, with no width limit: strip leading zeros,
/// then more digits means a larger number, then compare digit by digit.
fn cmp_digit_value(a: &str, b: &str) -> Ordering {
  let sa = a.trim_start_matches('0');
  let sb = b.trim_start_matches('0');
  sa.len().cmp(&sb.len()).then_with(|| sa.cmp(sb))
}

fn token_primary(t: &Token<'_>) -> (u8, u32) {
  match t {
    Token::Digits(d) => {
      let first = d.chars().next().expect("digit run is never empty");
      (CLASS_DIGIT, first as u32)
    }
    Token::Char { base, .. } => primary_key(*base),
  }
}

fn cmp_impl(a: &str, b: &str, numeric: bool) -> Ordering {
  let ta = tokenize(a, numeric);
  let tb = tokenize(b, numeric);

  // Pass 1 — primary: class, then base letter, ignoring case and accents.
  for (x, y) in ta.iter().zip(tb.iter()) {
    let ord = match (x, y) {
      (Token::Digits(da), Token::Digits(db)) => cmp_digit_value(da, db),
      _ => token_primary(x).cmp(&token_primary(y)),
    };
    if ord != Ordering::Equal {
      return ord;
    }
  }
  let len_ord = ta.len().cmp(&tb.len());
  if len_ord != Ordering::Equal {
    return len_ord;
  }

  // Pass 2 — secondary: unaccented before accented.
  for (x, y) in ta.iter().zip(tb.iter()) {
    if let (Token::Char { accent: aa, .. }, Token::Char { accent: ab, .. }) = (x, y) {
      let ord = aa.cmp(ab);
      if ord != Ordering::Equal {
        return ord;
      }
    }
  }

  // Pass 3 — tertiary: lowercase before uppercase.
  for (x, y) in ta.iter().zip(tb.iter()) {
    if let (Token::Char { raw: ca, .. }, Token::Char { raw: cb, .. }) = (x, y) {
      if ca != cb {
        let (la, lb) = (ca.is_lowercase(), cb.is_lowercase());
        if la != lb {
          return if la {
            Ordering::Less
          } else {
            Ordering::Greater
          };
        }
        return ca.cmp(cb);
      }
    }
  }

  // Pass 4 — equal-valued digit runs: fewer leading zeros first.
  for (x, y) in ta.iter().zip(tb.iter()) {
    if let (Token::Digits(da), Token::Digits(db)) = (x, y) {
      if da != db {
        return da.len().cmp(&db.len()).then_with(|| da.cmp(db));
      }
    }
  }

  // Identical at every level: fall back to raw bytes so the ordering is total.
  a.cmp(b)
}

#[cfg(test)]
mod tests {
  use super::{locale_cmp, natural_cmp};
  use std::cmp::Ordering;

  #[test]
  fn plain_compare_is_case_insensitive_first() {
    // Byte-wise ordering would put every uppercase letter first; localeCompare
    // does not, and neither do we.
    assert_eq!(locale_cmp("apple", "Banana"), Ordering::Less);
    assert_eq!(locale_cmp("Banana", "apple"), Ordering::Greater);
    assert_eq!(locale_cmp("ch01", "ch02"), Ordering::Less);
    assert_eq!(locale_cmp("same", "same"), Ordering::Equal);
  }

  #[test]
  fn lowercase_sorts_before_uppercase_on_ties() {
    assert_eq!(locale_cmp("a", "A"), Ordering::Less);
    assert_eq!(locale_cmp("A", "a"), Ordering::Greater);
  }

  #[test]
  fn unaccented_sorts_before_accented() {
    assert_eq!(locale_cmp("emile", "Émile"), Ordering::Less);
    assert_eq!(locale_cmp("resume", "résumé"), Ordering::Less);
    // Accents are ignored at the primary level, so they do not jump the letter.
    assert_eq!(locale_cmp("Émile", "zoe"), Ordering::Less);
  }

  #[test]
  fn punctuation_uses_icu_order_not_ascii_order() {
    // ASCII would put '-' (0x2D) before '_' (0x5F); ICU is the other way round.
    assert_eq!(locale_cmp("chapter_1", "chapter-1"), Ordering::Less);
    assert_eq!(locale_cmp("chapter 1", "chapter_1"), Ordering::Less);
  }

  #[test]
  fn punctuation_and_digits_sort_before_letters() {
    assert_eq!(locale_cmp("a-1", "aaa"), Ordering::Less);
    assert_eq!(locale_cmp("v1c1", "vol.1"), Ordering::Less);
  }

  #[test]
  fn plain_compare_does_not_treat_digits_numerically() {
    // `{ numeric: true }` is deliberately not the default, matching the old code.
    assert_eq!(locale_cmp("page10.png", "page2.png"), Ordering::Less);
  }

  #[test]
  fn numeric_compare_orders_digit_runs_by_value() {
    assert_eq!(natural_cmp("page2.png", "page10.png"), Ordering::Less);
    assert_eq!(natural_cmp("page10.png", "page2.png"), Ordering::Greater);
    assert_eq!(
      natural_cmp("ch1/page9.png", "ch1/page10.png"),
      Ordering::Less
    );
    assert_eq!(
      natural_cmp("ch9/page1.png", "ch10/page1.png"),
      Ordering::Less
    );
  }

  #[test]
  fn numeric_compare_ignores_leading_zeros_for_value() {
    assert_eq!(natural_cmp("page007.png", "page8.png"), Ordering::Less);
    assert_eq!(
      natural_cmp("page0000000000000000009.png", "page10.png"),
      Ordering::Less
    );
  }

  #[test]
  fn equal_valued_digit_runs_order_by_leading_zero_count() {
    assert_eq!(natural_cmp("page1.png", "page01.png"), Ordering::Less);
    assert_eq!(natural_cmp("page01.png", "page001.png"), Ordering::Less);
  }

  #[test]
  fn sorting_a_realistic_page_list() {
    let mut pages = vec![
      "page10.png",
      "page1.png",
      "page20.png",
      "page2.png",
      "page3.png",
    ];
    pages.sort_by(|a, b| natural_cmp(a, b));
    assert_eq!(
      pages,
      [
        "page1.png",
        "page2.png",
        "page3.png",
        "page10.png",
        "page20.png"
      ]
    );
  }

  /// A mixed corpus of the shapes that turn up in real manga libraries. Both
  /// expected orders below are verbatim output from a JS engine sorting this
  /// same list with `localeCompare`, so this test fails the moment the Rust
  /// ordering drifts from the behaviour the TypeScript code had.
  const CORPUS: [&str; 53] = [
    "page1.png",
    "page2.png",
    "page10.png",
    "page01.png",
    "page001.png",
    "Page3.png",
    "PAGE4.png",
    "ch1",
    "ch10",
    "ch2",
    "Ch3",
    "chapter 1",
    "chapter 10",
    "chapter 2",
    "chapter-1",
    "chapter_1",
    "One Piece",
    "one piece",
    "Berserk",
    "berserk",
    "Akira",
    "zzz",
    "ZZZ",
    "aaa",
    "AAA",
    "vol.1",
    "vol.10",
    "vol.2",
    "v1c1",
    "v1c10",
    "v1c2",
    "001.jpg",
    "010.jpg",
    "002.jpg",
    "漫画",
    "第1話",
    "第10話",
    "第2話",
    "Émile",
    "emile",
    "Zoe",
    "zoe",
    "a-1",
    "a-10",
    "a-2",
    "x 1",
    "x 10",
    "x 2",
    "",
    "0",
    "00",
    "1",
    "01",
  ];

  #[test]
  fn matches_js_plain_locale_compare_over_the_corpus() {
    let expected = [
      "",
      "0",
      "00",
      "001.jpg",
      "002.jpg",
      "01",
      "010.jpg",
      "1",
      "a-1",
      "a-10",
      "a-2",
      "aaa",
      "AAA",
      "Akira",
      "berserk",
      "Berserk",
      "ch1",
      "ch10",
      "ch2",
      "Ch3",
      "chapter 1",
      "chapter 10",
      "chapter 2",
      "chapter_1",
      "chapter-1",
      "emile",
      "Émile",
      "one piece",
      "One Piece",
      "page001.png",
      "page01.png",
      "page1.png",
      "page10.png",
      "page2.png",
      "Page3.png",
      "PAGE4.png",
      "v1c1",
      "v1c10",
      "v1c2",
      "vol.1",
      "vol.10",
      "vol.2",
      "x 1",
      "x 10",
      "x 2",
      "zoe",
      "Zoe",
      "zzz",
      "ZZZ",
      "漫画",
      "第10話",
      "第1話",
      "第2話",
    ];
    let mut got = CORPUS.to_vec();
    got.sort_by(|a, b| locale_cmp(a, b));
    assert_eq!(got, expected);
  }

  #[test]
  fn matches_js_numeric_locale_compare_over_the_corpus() {
    let expected = [
      "",
      "0",
      "00",
      "1",
      "01",
      "001.jpg",
      "002.jpg",
      "010.jpg",
      "a-1",
      "a-2",
      "a-10",
      "aaa",
      "AAA",
      "Akira",
      "berserk",
      "Berserk",
      "ch1",
      "ch2",
      "Ch3",
      "ch10",
      "chapter 1",
      "chapter 2",
      "chapter 10",
      "chapter_1",
      "chapter-1",
      "emile",
      "Émile",
      "one piece",
      "One Piece",
      "page1.png",
      "page01.png",
      "page001.png",
      "page2.png",
      "Page3.png",
      "PAGE4.png",
      "page10.png",
      "v1c1",
      "v1c2",
      "v1c10",
      "vol.1",
      "vol.2",
      "vol.10",
      "x 1",
      "x 2",
      "x 10",
      "zoe",
      "Zoe",
      "zzz",
      "ZZZ",
      "漫画",
      "第1話",
      "第2話",
      "第10話",
    ];
    let mut got = CORPUS.to_vec();
    got.sort_by(|a, b| natural_cmp(a, b));
    assert_eq!(got, expected);
  }
}
